name: Build
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: read
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ github.token }}
    - name: Make
      env:
        PKGFORGE_STATEFILE: /tmp/pkgforge
        GITHUB_TOKEN: ${{ github.token }}
      run: make
    - name: Release
      env:
        PKGFORGE_STATEFILE: /tmp/pkgforge
        GITHUB_TOKEN: ${{ github.token }}
      if: startsWith(github.ref, 'refs/tags/')
      run: make release
    - name: Store
      uses: actions/upload-artifact@v3
      with:
        name: pkg
        path: pkg
    - name: Post to a Slack channel
      if: ${{ always() }}
      uses: slackapi/slack-github-action@v1.18.0
      with:
        channel-id: ${{ secrets.SLACK_BOT_CHANNEL }}
        slack-message: "GitHub build result: ${{ job.status }}\n${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
